### ISSUE TITLE
Fix home maps not allowing gesture on mobile

### ISSUE THREAD

**Issue by guilhermedecampo** [Astrocoders/astrocoders-landing#13]

**Comment by eliabejr** [comment]
weird, tested here and it worked! but my phone is android

**Comment by medson10** [comment]
in mine it's not, is android also

**Comment by eliabejr** [comment]
what gestures have you tried?

**Comment by medson10** [comment]
wait, I'm confusing I guess, the issue is because it's scrolling the map or because it's not? Because in mine it's scrolling and didn't like it, it's disturbing for scroll the page, maybe just let the map fixed and put a link to open the map on google maps would be better

**Comment by eliabejr** [comment]
@guilhermedecampo can you confirm to us the expected behavior?

**Comment by guilhermedecampo** [comment]
Yes exactly. 

We should NOT allow gesture on map. It's annoying to scroll over it.

**Comment by eliabejr** [comment]
Fixed on #16
